import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 90,
    marginTop: 20,
  },
  linearGradient: {
    height: "100%",
    width: "100%",
  },
  title: {
    fontSize: 30,
    fontWeight: "700",
    color: "#FFF",
  },
  logoContainer: {
    marginTop: 90,
    alignItems: "center",
    //justifyContent: "center",
  },
  logo: {
    width: "100%",
    maxWidth: 300,
    height: 300,
  },
  buttonContainer: {
    width: "100%",
    marginTop: 10,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },

  buttonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
    textAlign: "center",
  },
  button: {
    backgroundColor: "#0782F9",
    width: "100%",
    padding: 15,
    borderRadius: 10,
    marginVertical: 10,
  },
  text: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFF",
    paddingBottom: 20,
    //width: '100%',
  },
  linearButton: {
    borderRadius: 10,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 30,
    padding: 20,
    paddingHorizontal: 100,
  },

  signupContainer: {
    width: "90%",
    alignItems: "center",
    backgroundColor: "white",
    padding: 25,
    borderRadius: 10,
  },
  registerContainer: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  loginContainer: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  textInput: {
    height: 50,
    width: "100%",
    borderColor: "gray",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
  },
  blackText: {
    fontSize: 20,
    fontWeight: "700",
    color: "black",
    //width: '100%',
    justifyContent: "center",
    alignItems: "center",
  },
  signinContainer: {
    width: "90%",
    alignItems: "center",
    backgroundColor: "white",
    padding: 25,
    borderRadius: 10,
  },
  chatInputContainer: {
    backgroundColor: "white",
    marginLeft: 16,
    height: "80%",
    width: "60%",
    padding: 20,
    flex: 1,
    alignContent: "center",

    borderColor: "#e8e8e8",
    borderWidth: 1,
    borderRadius: 5,

    paddingHorizontal: 0,
    marginBottom: 5,
  },
  searchContainer: {
    top: 20,
    left: 10,
    width: "90%",
    color: "white",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",

    backgroundColor: "transparent",
  },
  view: {
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  inputContainer: {
    height: 50,
    width: "90%",
    backgroundColor: "white",
    borderColor: "gray",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    marginLeft: 10,
  },
  input: {},
  scrollView: {
    backgroundColor: "#213B62",
  },
  editContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignSelf: "center",
    justifyContent: "center",
    marginRight: 55,
  },
  editInput: {
    borderBottomWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 8,
    marginBottom: 10,
  },
  preEditText: {
    fontSize: 16,
    marginBottom: 10,
  },
  editButton: {
    alignSelf: "center",
    padding: 10,
    backgroundColor: "#2196F3",
    borderRadius: 5,
    marginTop: 10,
  },
  editText: {
    color: "#fff",
    fontWeight: "bold",
  },
  signOutButton: {
    alignSelf: "center",
    padding: 100,
    backgroundColor: "#F44336",
    borderRadius: 5,
    marginTop: 20,
  },
  signOutText: {
    color: "#fff",
    fontWeight: "bold",
  },
  row: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginRight: 100,
  },
  bioRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 10,
    paddingHorizontal: 0,
    marginRight: 100,
    marginLeft: 30,
  },
  headerImage: {
    width: 40,
    height: 40,
    borderRadius: 50,
  },
  searchImage: {
    margin: 10,
    width: 80,
    height: 80,
    borderRadius: 50,
  },
  searchText: {
    color: "#fff",
    fontWeight: "bold",
  },
  formField: {
    borderWidth: 1,
    padding: 12,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 20,
    borderColor: "white",
    fontSize: 18,
    height: 50,
    width: 250,
    color: "white",
  },
  searchFriend: {
    marginLeft: 110,
  },
  cameraIcon: {
    marginLeft: 200,
  },
});
